services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
        - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
        - es-net

  fluent-bit:
    image: fluent/fluent-bit:2.1
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./logs:/fluentbit/logs
      
    depends_on:
      - elasticsearch
    networks:
      - es-net

  redis:
      image: redis:latest
      ports:
        - "6379:6379"  # Expose Redis on port 6379
      networks:
        - es-net

  go-app:
    build:
      context: .
    volumes:
      - ./logs/app.log:/app.log
    command: ["go", "run", "main.go"]

volumes:
  psql:
networks:
  es-net:
    driver: bridge
