// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"basic-to-advanced/di/google-wire-di/logger"
	"basic-to-advanced/di/google-wire-di/repo"
	"basic-to-advanced/di/google-wire-di/service"
)

// Injectors from wire.go:

func InitializeUserService() *service.UserService {
	userRepo := repo.NewMockUserRepo()
	loggerLogger := logger.NewLogger()
	userService := service.NewUserService(userRepo, loggerLogger)
	return userService
}
